import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { createHash } from "node:crypto";
import {
  acquireGeneratedLease,
  ownedGeneratedLeaseCount,
} from "../lease-transport.mjs";
import { copyGeneratedFixtureUnderLease } from "../lease-copy.mjs";
test("actual process exit with retained stdout revokes lease and copies zero generated bytes", async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentvac-lease-exit-")),
    source = await fs.open(path.join(root, "source"), "wx+"),
    destination = await fs.open(path.join(root, "empty"), "wx+");
  t.after(async () => {
    await source.close();
    await destination.close();
    if (process.platform !== "win32")
      await fs.rm(root, { recursive: true, force: true });
  });
  const payload = Buffer.from(
    "generated sentinel must not be copied after exit",
  );
  await source.writeFile(payload);
  const s = await destination.stat({ bigint: true });
  const request = {
    scope: "C:\\Research\\inherited-fixture-" + "1".repeat(32),
    path:
      "C:\\Research\\inherited-fixture-" +
      "1".repeat(32) +
      "\\private\\empty.bin",
    mode: "acl",
    directory: false,
    allowMissingLeaf: false,
    nonce: Buffer.alloc(16, 7),
  };
  const b = Buffer.alloc(96);
  b.writeUInt32LE(92);
  b.write("AVR2", 4);
  b[8] = 1;
  request.nonce.copy(b, 12);
  b.writeUInt32LE(64, 28);
  b.write("AVM2", 32);
  b[36] = 1;
  b[37] = 5;
  b.writeBigUInt64LE(s.dev, 40);
  b.writeBigUInt64LE(s.ino, 48);
  b.writeUInt32LE(1, 64);
  b.writeUInt32LE(32, 68);
  const code = `const {spawn}=require('node:child_process');spawn(process.execPath,['-e','setTimeout(()=>process.exit(0),350)'],{stdio:['ignore',1,2],env:{}}).unref();process.stdout.write(Buffer.from('${b.toString("hex")}','hex'));setTimeout(()=>process.exit(1),50);`;
  let child;
  const ready = acquireGeneratedLease({
    spawnPinned: () =>
      (child = spawn(process.execPath, ["-e", code], {
        stdio: ["pipe", "pipe", "pipe"],
        env: {},
      })),
    request,
  });
  const closed = once(child, "close"),
    exited = once(child, "exit");
  const lease = await ready;
  assert.equal((await exited)[0], 1);
  assert.equal(lease.isLive(), false);
  assert.equal(ownedGeneratedLeaseCount(), 1);
  await assert.rejects(
    copyGeneratedFixtureUnderLease({
      source,
      destination,
      lease,
      expectedBytes: payload.length,
      expectedSha256: createHash("sha256").update(payload).digest("hex"),
    }),
    (e) =>
      e.code === "LEASE_COPY_LOST" &&
      e.writtenKnown === 0 &&
      e.writeAttempted === false,
  );
  assert.equal((await destination.stat()).size, 0);
  await closed;
  assert.equal(ownedGeneratedLeaseCount(), 0);
});
