import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { createHash } from "node:crypto";
import {
  acquireGeneratedLease,
  ownedGeneratedLeaseCount,
} from "../lease-transport.mjs";
import { copyGeneratedFixtureUnderLease } from "../lease-copy.mjs";
test("actual exit revokes lease before close and copies zero generated bytes", { timeout: 5000 }, async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentvac-lease-exit-")),
    source = await fs.open(path.join(root, "source"), "wx+"),
    destination = await fs.open(path.join(root, "empty"), "wx+");
  t.after(async () => {
    await source.close();
    await destination.close();
    if (process.platform !== "win32")
      await fs.rm(root, { recursive: true, force: true });
  });
  const payload = Buffer.from(
    "generated sentinel must not be copied after exit",
  );
  await source.writeFile(payload);
  const s = await destination.stat({ bigint: true });
  const request = {
    scope: "C:\\Research\\inherited-fixture-" + "1".repeat(32),
    path:
      "C:\\Research\\inherited-fixture-" +
      "1".repeat(32) +
      "\\private\\empty.bin",
    mode: "acl",
    directory: false,
    allowMissingLeaf: false,
    nonce: Buffer.alloc(16, 7),
  };
  const b = Buffer.alloc(96);
  b.writeUInt32LE(92);
  b.write("AVR2", 4);
  b[8] = 1;
  request.nonce.copy(b, 12);
  b.writeUInt32LE(64, 28);
  b.write("AVM2", 32);
  b[36] = 1;
  b[37] = 5;
  b.writeBigUInt64LE(s.dev, 40);
  b.writeBigUInt64LE(s.ino, 48);
  b.writeUInt32LE(1, 64);
  b.writeUInt32LE(32, 68);
  const code = `process.on('message',message=>{if(message==='exit-generated')process.exit(1);else process.exit(3);});process.stdout.write(Buffer.from('${b.toString("hex")}','hex'));setTimeout(()=>process.exit(2),2000);`;
  let child, lease;
  let closeObserved = false;
  const ready = acquireGeneratedLease({
    spawnPinned: () =>
      (child = spawn(process.execPath, ["-e", code], {
        stdio: ["pipe", "pipe", "pipe", "ipc"],
        env: {},
      })),
    request,
  });
  const closed = once(child, "close");
  child.once("close", () => { closeObserved = true; });
  // Observe synchronously, after transport's exit listener and before close.
  // Awaiting exit permits the OS to deliver close before the continuation runs.
  const exited = new Promise((resolve) => child.once("exit", (code, signal) => {
    resolve({code, signal, live: lease?.isLive(), owned: ownedGeneratedLeaseCount(), closeObserved});
  }));
  t.after(async () => {
    if (!closeObserved) { child.kill(); await closed; }
  });
  lease = await ready;
  assert.equal(lease.isLive(), true);
  await new Promise((resolve, reject) => child.send("exit-generated", (error) => error ? reject(error) : resolve()));
  assert.deepEqual(await exited, {code: 1, signal: null, live: false, owned: 1, closeObserved: false});
  assert.equal(lease.isLive(), false);
  await assert.rejects(
    copyGeneratedFixtureUnderLease({
      source,
      destination,
      lease,
      expectedBytes: payload.length,
      expectedSha256: createHash("sha256").update(payload).digest("hex"),
    }),
    (e) =>
      e.code === "LEASE_COPY_LOST" &&
      e.writtenKnown === 0 &&
      e.writeAttempted === false,
  );
  assert.equal((await destination.stat()).size, 0);
  await closed;
  assert.equal(ownedGeneratedLeaseCount(), 0);
});
